### ISSUE TITLE
OKTW AND SEBBY BAN WARS 

### ISSUE THREAD

**Issue by yMeliodasNTD** [berbb/PortAIO-Loader#21] opened 2016-08-11 21:18 UTC
hey berb oktw crashing game sometimes when using the button of the lane clear ;/ (no erro in console),Sebby ban wars blocking ALL manual E whith vayne and Q whit sivir

**Comment by berbb** [comment] 2016-08-11 21:32
Sebby Ban Wars has that issue, it's not a bug. The original blocks spells also. I'll look into the lane clear error.

**Comment by yMeliodasNTD** [comment] 2016-08-11 22:09
it literally blocks all E manual or script

**Comment by berbb** [comment] 2016-08-12 20:23
Lane Clear shouldn't crash at all anymore, I can't guarantee it but I've added a lot of checks to make sure it doesn't do anything it shouldn't.

Fixed in 1.0.0.3.

**Closed by berbb** 2016-08-12 20:23 UTC
